import type { GeneratedTool } from "./generate.js";

/**
 * Renders tool contracts as YAML.
 *
 * Hand-written rather than using a YAML serialiser, because the exit criterion
 * is that regenerating produces an identical diff — and that requires control
 * over key order, quoting and line breaks that a general serialiser does not
 * give without fighting it. The output is a small, fixed subset of YAML.
 */

function scalar(value: unknown): string {
  if (value === null) return "null";
  if (typeof value === "boolean" || typeof value === "number") return String(value);

  const text = String(value);
  // Quote anything that could be misread as another YAML type, plus anything
  // containing characters that would change the parse.
  if (
    text === "" ||
    /^(true|false|null|yes|no|on|off|~)$/i.test(text) ||
    /^[-+]?[\d.]+$/.test(text) ||
    /[:#\-?{}[\],&*!|>'"%@`\n]/.test(text) ||
    text !== text.trim()
  ) {
    return `"${text.replace(/\\/g, "\\\\").replace(/"/g, '\\"').replace(/\n/g, "\\n")}"`;
  }
  return text;
}

function renderValue(value: unknown, indent: number): string {
  const pad = " ".repeat(indent);

  if (Array.isArray(value)) {
    if (value.length === 0) return "[]";
    return `\n${value.map((item) => `${pad}- ${renderValue(item, indent + 2).trimStart()}`).join("\n")}`;
  }

  if (value !== null && typeof value === "object") {
    const entries = Object.entries(value as Record<string, unknown>);
    if (entries.length === 0) return "{}";
    return `\n${entries
      .map(([key, child]) => {
        const rendered = renderValue(child, indent + 2);
        return rendered.startsWith("\n")
          ? `${pad}${scalar(key)}:${rendered}`
          : `${pad}${scalar(key)}: ${rendered}`;
      })
      .join("\n")}`;
  }

  return scalar(value);
}

/** One file per spec, listing every operation. Ordering is already stable. */
export function emitToolsYaml(source: string, tools: readonly GeneratedTool[]): string {
  const header = [
    "# GENERATED by @keel/tool-runtime from an OpenAPI specification.",
    "# Regenerate with: pnpm --filter @keel/tool-runtime generate",
    "#",
    "# Every operation is disabled. Turn on what the agent needs, one at a time,",
    "# and review the risk level — the generator sets a conservative default from",
    "# the HTTP method and cannot know your business consequences.",
    "#",
    "# `bind:` entries are sourced from the verified identity token or from static",
    "# config. They are deliberately absent from the input schema so the model",
    "# cannot supply them.",
    "",
    `keel: "1"`,
    "kind: tools",
    `source: ${scalar(source)}`,
    "tools:",
  ].join("\n");

  const body = tools
    .map((tool) => {
      const entries = Object.entries(tool).filter(([, v]) => v !== undefined);
      const [first, ...rest] = entries;
      if (first === undefined) return "";

      const firstLine = `  - ${first[0]}: ${renderValue(first[1], 6).trimStart()}`;
      const restLines = rest.map(([key, value]) => {
        const rendered = renderValue(value, 6);
        return rendered.startsWith("\n") ? `    ${key}:${rendered}` : `    ${key}: ${rendered}`;
      });
      return [firstLine, ...restLines].join("\n");
    })
    .join("\n");

  return `${header}\n${body}\n`;
}
