// @keel/contracts
// JSON Schemas, error taxonomy, event types and AG-UI mappings.
// Imported by everything, imports nothing from the workspace.

export {
  type ActivityEvent,
  AGUI_EVENT_TYPES,
  AGUI_MAPPING,
  type AguiEventType,
  type AguiMapping,
  activity,
  clientVisibleEvents,
  type EventChannel,
  feedsModelContext,
  isClientVisible,
  mappingFor,
} from "./agui.js";
export {
  type AgentLimitError,
  type ApprovalExpiredError,
  type ApprovalRejectedError,
  type ApprovalRequiredError,
  type AuthenticationError,
  type AuthorizationError,
  ERROR_CLASSES,
  type ErrorClass,
  type IntegrationError,
  isAgentLimitError,
  isApprovalExpiredError,
  isApprovalRejectedError,
  isApprovalRequiredError,
  isAuthenticationError,
  isAuthorizationError,
  isIntegrationError,
  isKeelError,
  isKnowledgeRetrievalError,
  isModelProviderError,
  isPolicyViolationError,
  isRateLimitError,
  isRetryable,
  isToolExecutionError,
  isToolTimeoutError,
  isToolUnavailableError,
  isToolValidationError,
  isWorkflowError,
  type KeelError,
  type KnowledgeRetrievalError,
  type ModelProviderError,
  type PolicyViolationError,
  type RateLimitError,
  retryAfterSeconds,
  shouldRetryToolCall,
  type ToolExecutionError,
  type ToolTimeoutError,
  type ToolUnavailableError,
  type ToolValidationError,
  type WorkflowError,
} from "./errors.js";
export {
  EVENT_TYPES,
  type EventOfType,
  type EventType,
  isEventOfType,
  type PlatformEvent,
  parsePlatformEvent,
  platformEventSchema,
} from "./events.js";
export {
  atLeastAsTrustedAs,
  checkI1,
  checkI2,
  combine,
  INTEGRITY_LEVELS,
  type IntegrityLevel,
  type InvariantCheck,
  isUntrusted,
  type Labelled,
  label,
  mapLabelled,
  meet,
} from "./integrity.js";
export {
  type EmitOptions,
  type EmitTarget,
  type JsonSchema,
  toInputJsonSchema,
  toJsonSchema,
} from "./json-schema.js";
export {
  APPROVAL_MODES,
  type ApprovalMode,
  type AuthBinding,
  authBindingSchema,
  cacheSchema,
  concurrencySchema,
  defaultApprovalMode,
  type Environment,
  errorClassSchema,
  idempotencySchema,
  jsonSchemaSchema,
  RISK_LEVELS,
  type RiskLevel,
  retrySchema,
  riskLevelSchema,
  SIDE_EFFECTS,
  type SideEffect,
  sideEffectSchema,
  TOOL_TARGETS,
  type ToolContract,
  type ToolContractInput,
  type ToolContractIssue,
  type ToolContractResult,
  type ToolTarget,
  toolContractSchema,
  toolExampleSchema,
  toolTargetSchema,
  type ValidateOptions,
  validateToolContract,
} from "./tool.js";
