import { type Palette, SCALE, THEMES } from "./tokens.js";

/**
 * Emits the stylesheet from the token data.
 *
 * Generated rather than hand-written so the CSS a browser renders and the values
 * the contrast check verifies are the same numbers by construction. A test
 * asserts the checked-in tokens.css matches this output, so a stale file fails
 * CI instead of quietly shipping unverified colours.
 */

const vars = (palette: Palette, indent: string): string =>
  Object.entries(palette)
    .map(([token, value]) => `${indent}--${token}: ${value};`)
    .join("\n");

const scaleVars = (): string => {
  const lines: string[] = [];
  for (const [size, value] of Object.entries(SCALE.fontSize)) {
    lines.push(`  --font-size-${size}: ${value};`);
  }
  for (const [step, value] of Object.entries(SCALE.space)) {
    lines.push(`  --space-${step}: ${value};`);
  }
  for (const [name, value] of Object.entries(SCALE.radius)) {
    lines.push(`  --radius-${name}: ${value};`);
  }
  for (const [name, value] of Object.entries(SCALE.duration)) {
    lines.push(`  --duration-${name}: ${value};`);
  }
  for (const [name, value] of Object.entries(SCALE.rowHeight)) {
    lines.push(`  --row-height-${name}: ${value};`);
  }
  return lines.join("\n");
};

export function emitTokensCss(): string {
  return `/* GENERATED by packages/ui/src/emit-css.ts — do not edit by hand.
   Run \`pnpm --filter @keel/ui build:tokens\` after changing src/tokens.ts.
   biome-ignore-all lint/complexity/noImportantStyles: the reduced-motion block
   at the end must beat every component transition, including ones added later */

:root,
[data-theme="dark"] {
${vars(THEMES.dark, "  ")}
}

[data-theme="light"] {
${vars(THEMES.light, "  ")}
}

:root {
  --font-sans: Inter, system-ui, -apple-system, "Segoe UI", sans-serif;
  --font-mono: "JetBrains Mono", ui-monospace, SFMono-Regular, Menlo, monospace;

${scaleVars()}

  /* The only shadow. Elevation is reserved for genuinely floating surfaces. */
  --shadow-overlay: 0 8px 24px -4px rgb(0 0 0 / 0.12);

  /* 2px ring, 2px offset, on everything focusable. Never outline: none. */
  --focus-ring: 0 0 0 2px var(--bg-canvas), 0 0 0 4px var(--border-focus);
}

/* Motion communicates state and nothing else, and a user who has asked for less
   of it gets none. !important is correct here and nowhere else: this rule has to
   beat every component's own transition, including ones added later, so a new
   animation cannot silently opt out of the preference. */
@media (prefers-reduced-motion: reduce) {
  *,
  *::before,
  *::after {
    animation-duration: 0.01ms !important;
    animation-iteration-count: 1 !important;
    transition-duration: 0.01ms !important;
    scroll-behavior: auto !important;
  }
}
`;
}
